# Generated by Django 4.0.8 on 2022-10-17 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPPrefix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=42, unique=True)),
                ('ping_task_state', models.CharField(default='Not Started', max_length=15)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'IP Address',
                'ordering': ['-ip'],
            },
        ),
        migrations.CreateModel(
            name='IPSubnets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subnet', models.CharField(blank=True, max_length=42, null=True)),
                ('status', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('parent_ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='childs', to='subnet_ip.ipprefix')),
            ],
            options={
                'verbose_name_plural': 'IP Subnets',
            },
        ),
    ]
