# Generated by Django 4.0.8 on 2024-07-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subnet_ip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipprefix',
            name='ping_task_state',
            field=models.CharField(max_length=15),
        ),
    ]
